spring:
  datasource:
    url: jdbc:mysql://localhost:3307/loja?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: im2402
  jpa:
    hibernate:
      ddl-auto: update
